---
- name: Install fedauth dependencies
  yum:
    name={{ item }}
    state=present
  with_items:
    - git

- name: Get portal from git
  git:
    repo=https://github.com/venekamp/fedauth-portal.git
    dest=/home/vagrant/fedauth-portal
  become_user: vagrant

- name: Copy portal to /var/www/fedauth-portal
  shell:
    rsync -a {{ item.src }} {{ item.dest }}
  with_items:
    - { src: /home/vagrant/fedauth-portal/fedauth-php, dest: /var/www/fedauth-portal/ }
    - { src: /home/vagrant/fedauth-portal/public,      dest: /var/www/fedauth-portal/ }
    - { src: /home/vagrant/fedauth-portal/cgi-bin/,    dest: /var/www/cgi-bin/ }

- name: Create portal apache conf file from template
  template: |
    src=fedauth-portal.conf.j2
    dest=/etc/httpd/conf.d/fedauth-portal.conf
    owner=root
    group=root
    mode=0644

- name: Create links to scripts
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
  with_items:
    - { src: /var/www/cgi-bin/get_secret.py,  dest: /var/www/fedauth-portal/fedauth-php/get_secret.py }
    - { src: /var/www/cgi-bin/user_local.py,  dest: /var/www/fedauth-portal/fedauth-php/user_local.py }
    - { src: /var/www/cgi-bin/user_mkpass.py, dest: /var/www/fedauth-portal/fedauth-php/user_mkpass.py }

- name: Restarting Apache
  service:
    name=httpd
    state=restarted
