---
- name: Set FQDN hostname
  hostname:
    name: "{{ hostname }}.{{ domainname }}"
  when:
    ansible_virtualization_type != "virtualbox"

- name: Setting /etc/hosts
  template: |
    src=hosts.j2
    dest=/etc/hosts
    mode=0644
    owner=root
    group=root
  when:
    ansible_virtualization_type != "virtualbox"
