---
- name: Creating RSA private key
  become_user: irods
  become: true
  command: openssl genrsa -out /etc/irods/server.key
  args:
    creates: /etc/irods/server.key

- name: Setting file permission on private key
  file:
    path=/etc/irods/server.key
    mode=0640

- name: Ensure openssl dir exists
  become_user: irods
  file:
    path: openssl
    state: directory
    mode: 0700

- name: Copy openssl config
  become_user: irods
  become: true
  template:
    src: openssl_irods.conf.j2
    dest: openssl/openssl_irods.conf
    mode: 0600

- name: Sign generated key
  become_user: irods
  become: true
  #  shell: openssl req -new -x509 -key /etc/irods/server.key -out /etc/irods/server.crt -days 365 < /vagrant/ansible/roles/irods_pam_authentication/files/certificate_info
  shell: openssl req -new -x509 -key /etc/irods/server.key -out /etc/irods/server.crt -config openssl/openssl_irods.conf
  args:
    creates: /etc/irods/server.crt

- name: Setting file permission on signed key
  file:
    path=/etc/irods/server.crt
    mode=0644

- name: Generate Diffie–Hellman parameters
  become_user: irods
  become: true
  command: openssl dhparam -2 -out /etc/irods/dhparams.pem 2048
  args:
    creates: /etc/irods/dhparams.pem

- name: Setting file permission on Diffie-Hellman file
  file:
    path=/etc/irods/dhparams.pem
    mode=0640

- name: Copying PAM stack for iRODS
  copy:
    src=roles/irods_pam_authentication/files/pam.d/irods
    dest=/etc/pam.d/irods
    owner=irods
    group=irods
    mode=0644
