---
- name: Install sssd and dependencies
  yum:
    name: sssd
    state: present

- name: Configure sssd
  template:
    src: {{ item.src }}
    dest: {{ item.dest }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: "sssd.conf.j2",     dest: "/etc/sssd/sssd.conf" }
    - { src: "nsswitch.conf.j2", dest: "/etc/nsswitch.conf"  }

- name: Start sssd
  service:
    name: sssd
    state: started
