---
- name: Install sssd and dependencies
  yum:
    name: sssd
    state: present

- name: Configure sssd
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: Start sssd
  service:
    name: sssd
    state: started
